//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workshop_5_Group_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Package
    {
        public Package()
        {
            this.Bookings = new HashSet<Booking>();
            this.Products_Suppliers = new HashSet<Products_Suppliers>();
        }
    
        public int PackageId { get; set; }
        public string PkgName { get; set; }
        public Nullable<System.DateTime> PkgStartDate { get; set; }
        public Nullable<System.DateTime> PkgEndDate { get; set; }
        public string PkgDesc { get; set; }
        public decimal PkgBasePrice { get; set; }
        public Nullable<decimal> PkgAgencyCommission { get; set; }
        public string PkgImg { get; set; }
    
        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Products_Suppliers> Products_Suppliers { get; set; }
    }
}
