//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workshop_5_Group_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Products_Suppliers = new HashSet<Products_Suppliers>();
        }
    
        public int ProductId { get; set; }
        public string ProdName { get; set; }
    
        public virtual ICollection<Products_Suppliers> Products_Suppliers { get; set; }
    }
}
