//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Workshop_5_Group_3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products_Suppliers
    {
        public Products_Suppliers()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
            this.Packages = new HashSet<Package>();
        }
    
        public int ProductSupplierId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> SupplierId { get; set; }
    
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual ICollection<Package> Packages { get; set; }
    }
}
